CREATE TABLE Employees(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
NAME VARCHAR(255),
FIRSTNAME VARCHAR(255),
HOMEPHONE VARCHAR(255),
MOBILEPHONE VARCHAR(255),
WORKPHONE VARCHAR(255),
ADDRESS VARCHAR(255),
POSTALCODE VARCHAR(255),
CITY VARCHAR(255),
EMAIL VARCHAR(255),

PRIMARY KEY (ID)
)